### ISSUE TITLE
Popping out Actors Tab pulls up last actor sheet instead

### ISSUE THREAD

**Issue by TEUSnoopy** [iotech-fvtt/flexui#15]
**What version of FlexUI are you using?**
0.3.0
**What version of Foundry are you using?**
11.307
**Do you have any other UI-changing mods activated?**
No
**Describe the bug**
Popping out the Actors tab results in pulling up last opened Actor sheet instead.

**To Reproduce**
1. Right click on Actor icon for FlexUI
2. Actor sheet revealed

**Expected behavior**
Actor view should pop out onto VTT as a movable window.

**Screenshots**
None required

**How Are you running Foundry?:**
 - Foundry Antive App:
 - OS: Windows Server 2016
 - Browser: Chrome 115.0.5790.111
 - Self hosting 

**Additional context**

**Comment by iotech-fvtt** [comment]
Foundry v11.307 also does this with FlexUI removed; it isn't a FlexUi bug,
it's a Foundry bug.

**Comment by TEUSnoopy** [comment]
Looks like you're correct. I should've dug deeper; my apologies. More specifically, it is not a Core bug, but likely a conflict with an existing module. I'll see if I can figure out which one it is. Thanks for the response.

**Comment by TEUSnoopy** [comment]
_Monk's Little Details_ causes this behavior. 

Thank you for your time and keeping this module alive. I consider it a must-have.

**Comment by iotech-fvtt** [comment]
Thank you for taking the time to figure it out. I just re-enabled MLD
yesterday, guess I will be turning it off again!
