### ISSUE TITLE
Please can an icon be added to File Browser in Classic Fantasy UI? 

### ISSUE THREAD

**Issue by YenBenGrey** [iotech-fvtt/flexui#16]
##FlexUI is intended to be very "code-light", meaning I will not be adding a lot of functionality or logic to it because that will certainly interfere with other mods. I try to prevent FlexUi from colliding with other modes except those which replace the sidebar UI.##

**Is your feature request related to a problem? Please describe.**
On the Classic Fantasy UI setting the File Browser icon is just a tiny white folder, in the regular fantasy UI it is a beautiful book.

**Describe the solution you'd like**
Please can File Browser in Classic Fantasy have a book icon

**Describe alternatives you've considered**

**Additional context**
<img width="249" alt="image" src="https://github.com/iotech-fvtt/flexui/assets/98095856/274029aa-9eb7-4a2e-81af-bc7eb7c4995f">

**Comment by YenBenGrey** [comment]
Well I am absolutely shocked, I have managed to do it myself. 

However I will lock the module now so that I don't overwrite it, please can this be a permanent fixture for the future?

<img width="249" alt="image" src="https://github.com/iotech-fvtt/flexui/assets/98095856/4d94b38f-3839-401c-a958-0c6ed7315afe">

**Comment by iotech-fvtt** [comment]
Well done! I'll add this to my to-do list buit it may be some time before I
release an update  (I want to see what v12 will require).

**Comment by YenBenGrey** [comment]
Hey there are you doing any updates soon? Unfortunately it clashes with TheRipper's Omnisearch :-(
