### ISSUE TITLE
Good work on the new version!

### ISSUE THREAD

**Issue by Darkiller25** [iotech-fvtt/flexui#2]
Sorry didn't know where to go write to you so here it is!

**Comment by iotech-fvtt** [comment]
You can reach me at gerry (at) E911systems (dot) com if you want to discuss in private.

Glad you're liking it!

**Comment by iotech-fvtt** [comment]
First public release:
https://github.com/iotech-fvtt/flexui/releases/tag/0.1.3
https://raw.githubusercontent.com/iotech-fvtt/flexui/master/module.json
