### ISSUE TITLE
Awesome new module :)

### ISSUE THREAD

**Issue by Darkiller25** [iotech-fvtt/flexui#3]
Good job on the module, and having the different options available is a blessing (and per user on top of that!).

One question though... where are the buttons that used to be in FantasyUI and V2? I like the new fantasy version, but I wanted to compare :P

**Comment by iotech-fvtt** [comment]
All of the assets from FantasyUI V2 are still in FantasyUI, still available on the FoundryVTT.com modules list. You can have both v2 and FlexUI installed at the same time (but only one activated, please). Older versions of FantasyUI can also be had on the same page in the modules list. 

That said, the next Big Thing (TM) for FlexUI will be a "build it yourself" theme, where you can add your own images for buttons and icons. Or maybe I'll do a "classic" theme. Which buttons in particular are you pining for?

**Comment by Darkiller25** [comment]
ahh makes sense! And yes I love the fact that we can customize it (per user) :D 

Hmm... it would be the ones in the FantasyV2 version, I liked the right bar ones (the images for the tabs are perfect like this).

**Comment by iotech-fvtt** [comment]
The tab icons are exactly the same in FantasyUI v2 vs FlexUI (Fantasy theme). You must be talking about the folder buttons.. 
FantasyUI:
![chrome_5qpiEg3n9U](https://user-images.githubusercontent.com/29070865/160188560-c3b286bb-6db9-43ae-80c1-21d3b8129b0c.png)
vs FlexUI:
![chrome_gaT6PNGCtj](https://user-images.githubusercontent.com/29070865/160188593-f65e28e4-bfbd-4e64-8a9c-649a3e81e00c.png)

**Comment by Darkiller25** [comment]
oops yeah I meant the folder buttons :p

**Comment by iotech-fvtt** [comment]
I could maybe do a Classic theme that looks just like FantasyUI v2.

**Comment by Darkiller25** [comment]
I mean... you don't HAVE to, but I would be glad to have that option :)

**Comment by Darkiller25** [comment]
Also, I noticed two issues with the Fantasy theme (haven't checked the other 2 for this) but some folders are not properly aligned (even though it's only one word) and when you right-click on a folder, the text below looks blurry for some reason
![NewUI](https://user-images.githubusercontent.com/71094682/160199007-a45245d1-ff9d-4fb7-8544-dbb76c9a0253.png)

**Comment by iotech-fvtt** [comment]
You're right on both accounts. New issues created.

**Comment by Darkiller25** [comment]
oops, yeah as a former QA tester... I should have written this properly :p

**Comment by iotech-fvtt** [comment]
Completed, will in release v0.1.5
