### ISSUE TITLE
Classic Fantasy Theme "Font"and "folder Icon" Color

### ISSUE THREAD

**Issue by Nostalgia2046** [iotech-fvtt/flexui#7]
Hello friend ! 

So I'm super happy to find the classic Fantasy Ui in all its glory (and the newly added Card icon). I do have an issue though with the black color used for the Font and Folder icon. I can barely read them :/ Is there anyway to change the color of it ? Maybe by myself so I can test out different possibilites ? 

Here's a screenshot (attached file)

![Capture](https://user-images.githubusercontent.com/97110801/164838167-54d0b4c3-4ff9-4454-a4a0-46583ba42788.JPG)

**Comment by iotech-fvtt** [comment]
I agree it is harder to read than it needs to be, Will fix.

**Comment by Nostalgia2046** [comment]
Thanks iotech, in the meantime, I just changed the background of each folder, but I guess there must be an overall good color pick for that ? I guess maybe white ? Really no idea haha

**Comment by iotech-fvtt** [comment]
There is the rub... with benign able to adjust the color of the folder,
some colors just dont look good with the white/black on the font. I could
maybe add being able to tweak the font color and shadow to the user
settings, then users could find their own combination that looks good to
them. Have to think on that.

**Comment by Nostalgia2046** [comment]
For the user to be able to change this at will would be incredible.  Hopefully it's not to difficult to integrate ! :)

**Comment by Mist-Hunter** [comment]
Thank you so much for you skin. I have never been tempted to reskin Foundry as most of the skins aren't up my alley. The icons are so much more clear and color themes are great.

I would, however, like to add to the feedback here that I think folders images in general slightly detract from my ability to quickly identify the folder I'm looking for. This is totally subjective, but here's an example:

![image](https://user-images.githubusercontent.com/6420684/168118842-ca206f3e-d676-4371-970c-4242eb82ae18.png)

In my opinion, when quickly looking at the image, my eyes are drawn to the folder borders, and then the actor icon, before being able to read the text. IMO the text should be more prominent and the folder UI image should draw less attention.

Either way, thank you so much for this skin.

**Comment by iotech-fvtt** [comment]
Thanks for the feedback and kind words, Zuckuss! I'm not totally satisfied
with the folder button either. Not sure yet what I will be doing about it,
but it is in the plan.

**Comment by iotech-fvtt** [comment]
Wanted to update you on this issue. I WILL fix this, but not sure when just yet. IRL things. It shouldnt be too long though.

**Comment by iotech-fvtt** [comment]
Fix for this is coming TODAY along with v10 compatibility and visual fixes to Classic and Fantasy themes.

**Comment by iotech-fvtt** [comment]
@Mist-Hunter Still have not fixed the button background thing, but I have an idea on that. Please open a new issue on that so it doesnt get lost when I close this issue.

**Comment by iotech-fvtt** [comment]
Issue closed; corrected in v2.0.0 release later today

**Comment by Nostalgia2046** [comment]
Fantastic, will check out the update !
